### PR TITLE
[discussion] pool ssl/tls connections - alternative 2

### LINKED ISSUE #161: connect_proxy with pooled connection fails
Here I am trying setup http connections though a proxy over tls, if I close the connection, it works but when I set keep_alive, request randomly fails, probably when pooled connection is used again. Am I doing something wrong here?

```lua
-- docker run -d -p 3128:3128 wernight/squid

local cjson = require("cjson")
local http = require "resty.http"


local function send(keep_alive)

	local httpc = http.new()

	httpc:set_timeout(5000)
	

	local ok, err = httpc:connect_proxy("http://localhost:3128", "https", "httpbin.org", 443)
	if not ok then
	  ngx.say("failed to connect: ", err)
	  return
	end


	local ok, err = httpc:ssl_handshake(nil, 'www.httpbin.org', false)
	if not ok then
	  ngx.say("failed to ssl_handshake: ", err)
	  return
	end

	local res, err = httpc:request({
	  method = 'GET',
	  path = 'https://www.httpbin.com:443/get',
	  headers = {
	    ['Host'] = 'www.httpbin.org',
	    ['User-Agent'] = 'curl/7.38.0'
	  }
	})

	if not res then
	  ngx.say("failed to request: ", err)
	  return
	end

	local body, err = res:read_body()
	if body then
	  res.body = body
	end

	ngx.say("status: ", res.status)
	ngx.say("headers: ", cjson.encode(res.headers))
	ngx.say("body: ", res.body)


	if keep_alive then
	   httpc:set_keepalive()
	end
end

for i=1,10 do
	print("==========request", i, "============")
	send()
end

for i=1,10 do
	print("==========request with keep_alive", i, "============")
	send(true)
end
```

### PR DESCRIPTION
**Pull request by Tieske**
Here's the second option for safe keep-alive across ssl + proxy connections.

It implements a new connect method that does it all at once (connect, ssl-handshake, proxy)

This is (imo the better) alternative to https://github.com/ledgetech/lua-resty-http/pull/202 .

There are no tests since this is very hard to test without a proxy server. Yet tests are available in the originating code here: https://github.com/Kong/kong-plugin-aws-lambda/compare/better-connect?expand=1 , which includes a forward-proxy and full integration tests.

Input is appreciated  @hamishforbes @pintsized @bungle .

replaces #201 
fixes #161 
replaces #205

### CODE REVIEW

File: lib/resty/http.lua [hunk 1]
```diff
@@ -174,8 +174,23 @@ function _M.ssl_handshake(self, ...)
...
+            return self:old_connect(options, ...)
+        end
+    end
+end
 
-function _M.connect(self, ...)
+function _M.old_connect(self, ...)
     local sock = self.sock
     if not sock then
         return nil, "not initialized"
```
Comment (pintsized) [inline lib/resty/http.lua:196]: I prefer the way this is explained in the docs to the way to code reads - i.e. "all-in-one" vs "tcp-only". Can we avoid naming the original function `old_connect`? To me I think it makes sense to have `connect` dispatch to either `tcp_only_connect` or `all_in_one_connect`, based on the arg types.

**Comment by Tieske** [comment]
@pintsized all updates done, please have another look

**Comment by Tieske** [comment]
> I would really like to have tests around this stuff, as well as the existing forwarding proxy connection code. This was contributed code and not a use case of mine, so I've always been a bit nervous about it. I've just got travis builds working. I'm wondering if we can do something with Docker Compose to test against a forwarding proxy?

Here's what we are using (docker-compose based):
 - squid: https://github.com/Kong/kong-pongo/blob/3ccaf860e101b9967c0aafa7a7d5d9b9eea5a148/assets/docker-compose.yml#L55-L68
 - squid config: https://github.com/Kong/kong-pongo/blob/3ccaf860e101b9967c0aafa7a7d5d9b9eea5a148/assets/squid.conf
 - squid auth: https://github.com/Kong/kong-pongo/blob/3ccaf860e101b9967c0aafa7a7d5d9b9eea5a148/assets/squid.passwords
 - some docs: https://github.com/Kong/kong-pongo/blob/3ccaf860e101b9967c0aafa7a7d5d9b9eea5a148/README.md#test-dependencies
 - and the tests: https://github.com/Kong/kong-plugin-aws-lambda/blob/d4e3e6d774292c805ae9d46de5610ab78c3dd9c6/spec/plugins/aws-lambda/50-http-proxy_spec.lua

**Comment by Tieske** [comment]
@pintsized any updates?

PS. CI seems to be in a weird state. I can't click any of the links to check what's wrong?

**Comment by Tieske** [comment]
ping

**Comment by pintsized** [comment]
Hey, sorry (again) for being so slow. Things are pretty hectic for me at the moment.

It's passing local tests fine, I think it's just because your PR was submitted before I got Travis working - Github isn't getting the notification or something. Of course the important tests are the ones you're hosting (thanks for sending the details over).

My only concern with all of this is the amount of code duplication. Could / should `request_uri` (i.e. the simple path) not use your connector module instead? So the user would call `set_proxy_options` as they currently do if using `request_uri`, and it would just pass this to your interface? Ditto for `connect_proxy` actually, so we keep what we have to from the old API, but utilise your module?

I appreciate it's a bit of a mess at this stage, and that your contribution here is important for correctness. If we can push the old interface towards using this new code somehow, things will be much less likely to rot.

Having said all of this, I really don't have any time to work on it at the moment, and so if we need to merge this and come back to it, I can live with that. I'll hopefully have some proper time in a month or so. At which point I'd be keen to get something like your integration tests setup for this.

Thanks for your input, and sorry for not being more responsive!

**Comment by Tieske** [comment]
@pintsized I updated the PR. I squashed the original PR into a single commit and added/changed step-by-step, to make the short hand method use the aio connect method (and fix some bugs that popped up).

I made an effort to make commits atomic so for review it is probably easiest to review individual commits.

Can you please have another look?

**Comment by pintsized** [comment]
Awesome man, thanks for the effort here. I'll go through it properly by the end of the week.

**Comment by Tieske** [comment]
there was another flaky test, updated the commit and pushed again, CI is green now.

File: lib/resty/http_connect.lua [hunk 2]
```diff
@@ -0,0 +1,234 @@
...
+    -- construct a poolname unique within proxy and ssl info
+    if not poolname then
+        poolname = (request_scheme or "")
+                   .. ":" .. request_host
+                   .. ":" .. tostring(request_port)
+                   .. ":" .. tostring(ssl)
+                   .. ":" .. (ssl_server_name or "")
+                   .. ":" .. tostring(ssl_verify)
+                   .. ":" .. (proxy_uri or "")
+                   .. ":" .. (request_scheme == "https" and proxy_authorization or "")
```
Comment (pintsized) [inline lib/resty/http_connect.lua:159]: It's probably worth creating a table and using `table.concat` here, to reduce the number of allocations.

File: README.md [hunk 3]
```diff
@@ -151,14 +151,53 @@ Creates the http object. In case of failures, returns `nil` and a string describ
 
 ## connect
 
+`syntax: ok, err = httpc:connect(aio_options_table)`
+
 `syntax: ok, err = httpc:connect(host, port, options_table?)`
```
Comment (pintsized) [inline README.md:157]: Do you think perhaps we should deprecate the old interface? Seems like we could use your new interface, without ssl or proxy options, and get the same behaviour without much cost?

**Review by pintsized — CHANGES_REQUESTED** [review]
OK, looking good :+1: 

Aside from the minor comments that I added, my only real concerns are the test coverage and the increased API surface.

For the test coverage, the major difference seems to be that `connect_proxy` no longer has any coverage at all. Am I right in thinking this method is really only there for backwards compatibility with code using the generic interface? I personally have almost no experience with forward proxy semantics, and all of the use cases here have been contributed by others. I'm more than a little nervous about breaking things I don't understand ;)

But this leads me to wonder if we should be marking anything as deprecated whilst we're at it? I guess I'm thinking; if someone new comes to this module, are we making it clear enough what they should reach for first, since they now have even more options? Seems like we could deprecate the old `connect` signatures, and also the `connect_proxy` method?

I guess that includes `ssh_handshake` too. Originally I just tried to keep the interface similar to the other cosocket modules, but the reality is that HTTP semantics are just more complicated than that, and my sense is we should encourage everyone to use your "all in one" method, right? Can you think of use cases that aren't covered by that?

I think we're also missing test coverage for a non `https` proxy, but that appears to be true on the master branch too.

Again, thanks for all the effort here.

File: lib/resty/http_connect.lua (hunk 2 above)
Comment (Tieske) [reply lib/resty/http_connect.lua:159]: this is a single concat operation. If you do it in a loop, then it would be multiple.

File: README.md [hunk 4]
```diff
@@ -151,14 +151,53 @@ Creates the http object. In case of failures, returns `nil` and a string describ
...
+
+This version of connect uses the `aio_options` signature above. For the
+other signatures see the [TCP only connect](#tcp-only-connect) below.
+
+This version of `connect` will connect to the remote end while incorporating the
+following activities:
+
+- TCP connect
+- SSL handshake
+- HTTP-proxy (options to be set using [set_proxy_options](#set_proxy_options))
```
[the remark this answers is not in the document]
Comment (Tieske) [reply README.md:172]: I changed it a couple of times over commits, final versions reads:
```
proxy_opts,             -- proxy opts, defaults to global proxy options
```

File: lib/resty/http.lua [hunk 5]
```diff
@@ -654,7 +680,7 @@ function _M.send_request(self, params)
     params.headers = headers
 
     -- Format and send request
-    local req = _format_request(params)
+    local req = _format_request(self, params)
```
[the remark this answers is not in the document]
Comment (Tieske) [reply lib/resty/http.lua:683]: No, `_format_request` is a local function that doesn't live on the module table `_M`. Unless there is a reason for exporting it on the module table, it should stay as it is imo.

File: lib/resty/http_connect.lua [hunk 6]
```diff
@@ -0,0 +1,234 @@
...
+        if proxy.no_proxy == "*" then
+            -- all hosts are excluded
+            proxy = nil
+
+        else
+            local host = request_host
+            local no_proxy_set = {}
+            -- wget allows domains in no_proxy list to be prefixed by "."
+            -- e.g. no_proxy=.mit.edu
+            for host_suffix in ngx_re_gmatch(proxy.no_proxy, "\\.?([^,]+)") do
```
[the remark this answers is not in the document]
Comment (Tieske) [reply lib/resty/http_connect.lua:108]: no reason, fixed

File: README.md (hunk 3 above)
Comment (Tieske) [reply README.md:157]: yes.

These days everything is ssl mostly. Doing the steps manual is causing a lot of code duplication, and is very tedious because there are so many edge cases one needs to think of. A lot of parameters to each of the `connect`, `handshake`, and `proxy` calls share a lifetime over all the three methods.

That is exactly what caused me to rewrite the whole thing, such that it would be less error prone.

**Comment by Tieske** [comment]
> OK, looking good 👍
> 
> Aside from the minor comments that I added, my only real concerns are the test coverage and the increased API surface.
> 
> For the test coverage, the major difference seems to be that `connect_proxy` no longer has any coverage at all. Am I right in thinking this method is really only there for backwards compatibility with code using the generic interface?

Yes

> I personally have almost no experience with forward proxy semantics, and all of the use cases here have been contributed by others. I'm more than a little nervous about breaking things I don't understand ;)
> 
> But this leads me to wonder if we should be marking anything as deprecated whilst we're at it? I guess I'm thinking; if someone new comes to this module, are we making it clear enough what they should reach for first, since they now have even more options? Seems like we could deprecate the old `connect` signatures, and also the `connect_proxy` method?
> 
> I guess that includes `ssh_handshake` too.

Yes probably all three should be deprecated, and examples updated to use the aio method

> Originally I just tried to keep the interface similar to the other cosocket modules, but the reality is that HTTP semantics are just more complicated than that, and my sense is we should encourage everyone to use your "all in one" method, right? Can you think of use cases that aren't covered by that?

Nope

> 
> I think we're also missing test coverage for a non `https` proxy, but that appears to be true on the master branch too.
> 
> Again, thanks for all the effort here.

👍

**Comment by pintsized** [comment]
Ok, I'll merge this and rework the docs, deprecating the old connection syntax.

**Comment by Tieske** [comment]
Nice! 🎉

**Comment by Tieske** [comment]
@pintsized fyi: I just created an [updated version of the Kong Lambda plugin](https://github.com/Kong/kong-plugin-aws-lambda/pull/50) which has integration tests for keepalive and proxy connections. The tests in the branch run against the master branch of the http client. [Everything is green](https://travis-ci.com/github/Kong/kong-plugin-aws-lambda/jobs/490860765#L797-L822).

Just extra confirmation all seems well, since proxy tests are lacking in the lib.

**Comment by pintsized** [comment]
Nice, good to know! I'll cut a new release soon...
