### PR TITLE
fix poolname to include the digest of the cert for mTLS

### LINKED ISSUE #306: The poolname doesn't include the client cert info for mtls authentication
For https requests, if the `ssl_client_cert` is set, then the [poolname](https://github.com/ledgetech/lua-resty-http/blob/master/lib/resty/http_connect.lua#L165-L172) should include a field (e.g. the digest of cert) to distinguish different clients. Otherwise, there will be a security issue where any users can reuse the connections of other authenticated users.

I'm preparing a fix for this and wondering if you mind introducing the dependency of `lua-resty-openssl` into this library. We can address the cdata of X509 and calculate the digest easily by using`lua-resty-openssl`. Otherwise we have to call those OpenSSL APIs ourselves by using ffi.

### PR DESCRIPTION
**Pull request by catbro666**
Fix https://github.com/ledgetech/lua-resty-http/issues/306

Additionally, add the latest openresty versions in CI. OpenResty has already supported `tcpsock:setclientcert` from 1.21.4.2 so only skip the mtls tests when version < 1.21.4

### CODE REVIEW

**Comment by catbro666** [comment]
Hi @pintsized could you review and merge this when you have time?

File: lib/resty/http_connect.lua [hunk 1]
```diff
@@ -160,16 +165,107 @@ local function connect(self, options)
...
     if not poolname then
-        poolname = (request_scheme or "")
-                   .. ":" .. request_host
-                   .. ":" .. tostring(request_port)
-                   .. ":" .. tostring(ssl)
-                   .. ":" .. (ssl_server_name or "")
-                   .. ":" .. tostring(ssl_verify)
-                   .. ":" .. (proxy_uri or "")
-                   .. ":" .. (request_scheme == "https" and proxy_authorization or "")
+        poolname = string_format("%s:%s:%s:%s:%s:%s:%s:%s:%s",
```
Comment (tzssangglass) [inline lib/resty/http_connect.lua:259]: log the `poolname` so we can check this easily in test cases?

Comment (tzssangglass) [reply lib/resty/http_connect.lua:260]: agree

**Comment by catbro666** [comment]
ping this

**Review by tzssangglass — APPROVED** [review]
LGTM

**Comment by catbro666** [comment]
ping @pintsized This one has been open for a long time. Could you have a look?

**Comment by pintsized** [comment]
> ping @pintsized This one has been open for a long time. Could you have a look?

Sorry, I have no time to look at this at the moment. I'd appreciate some more eyes on it if anyone has time, perhaps some Kong folk? @Tieske @chronolaw

File: lib/resty/http_connect.lua [hunk 2]
```diff
@@ -160,22 +166,115 @@ local function connect(self, options)
         proxy_port = proxy_uri_t[3]
     end
 
+    local cert_hash
+    if ssl and ssl_client_cert and ssl_client_priv_key then
+        -- fallback to non-mTLS when any error
+        repeat
+            local cert_type = type(ssl_client_cert)
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:173]: Should we localize `type`?

File: lib/resty/http_connect.lua [hunk 3]
```diff
@@ -160,22 +166,115 @@ local function connect(self, options)
...
+                ngx_log(ngx_WARN, "bad ssl_client_cert: cdata expected, got " .. cert_type)
+                break
+            end
+
+            if key_type ~= "cdata" then
+                ngx_log(ngx_WARN, "bad ssl_client_priv_key: cdata expected, got " .. key_type)
+                break
+            end
+
+            local status, res = xpcall(function()
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:186]: Could we change this anonymous function to a local function? It may cause NYI.

File: lib/resty/http_connect.lua [hunk 4]
```diff
@@ -160,22 +166,115 @@ local function connect(self, options)
...
+                cert_hash, err = cert:digest("sha256")
+                if cert_hash then
+                    cert_hash = to_hex(cert_hash) -- convert to hex so that it's printable
+
+                else
+                    ngx_log(ngx_WARN, "failed to calculate the digest of the cert, falling back to non-mTLS: " .. err)
+                    break
+                end
+
+            else
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:241]: It is a big `if-else`, could we refactor it with `goto continue`?

File: lib/resty/http_connect.lua [hunk 5]
```diff
@@ -160,22 +166,115 @@ local function connect(self, options)
...
+
+            if status then
+                local chain = res[1]
+                local x509 = res[2]
+                local pkey = res[3]
+
+                -- convert from `void*` to `OPENSSL_STACK*`
+                local cert_chain, err = chain.dup(ffi_cast("OPENSSL_STACK*", ssl_client_cert))
+                if not cert_chain then
+                    ngx_log(ngx_WARN, "failed to dup the ssl_client_cert, falling back to non-mTLS: " .. err)
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:201]: Should we use `ngx.log(ngx.XXX, a, b, c)` to avoid string concat?

File: lib/resty/http_connect.lua (hunk 2 above)
Comment (catbro666) [reply lib/resty/http_connect.lua:181]: done.

File: lib/resty/http_connect.lua [hunk 6]
```diff
@@ -160,22 +174,112 @@ local function connect(self, options)
...
-                   .. ":" .. tostring(request_port)
-                   .. ":" .. tostring(ssl)
-                   .. ":" .. (ssl_server_name or "")
-                   .. ":" .. tostring(ssl_verify)
-                   .. ":" .. (proxy_uri or "")
-                   .. ":" .. (request_scheme == "https" and proxy_authorization or "")
+        poolname = string_format("%s:%s:%s:%s:%s:%s:%s:%s:%s",
+                    request_scheme or "",
+                    request_host,
+                    tostring(request_port),
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:268]: Since we are using `string.format("%s")`, `tostring()` is unnecesssary now.

File: lib/resty/http_connect.lua [hunk 7]
```diff
@@ -160,22 +174,112 @@ local function connect(self, options)
...
+
+            -- check the private key in order to make sure the caller is indeed the holder of the cert
+            ok, err = cert:check_private_key(key)
+            if not ok then
+                ngx_log(ngx_WARN, "the private key doesn't match the cert, falling back to non-mTLS: ", err)
+                break
+            end
+
+            cert_hash, err = cert:digest("sha256")
+            if cert_hash then
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:247]: It could be:
```
if  not cert_hash then
  ngx_log(...)
  break
end
```

File: lib/resty/http_connect.lua (hunk 6 above)
Comment (catbro666) [reply lib/resty/http_connect.lua]: indeed.

File: lib/resty/http_connect.lua (hunk 7 above)
Comment (catbro666) [reply lib/resty/http_connect.lua]: applied

File: lib/resty/http_connect.lua [hunk 8]
```diff
@@ -160,22 +174,111 @@ local function connect(self, options)
         proxy_port = proxy_uri_t[3]
     end
 
+    local cert_hash
+    if ssl and ssl_client_cert and ssl_client_priv_key then
+        -- fallback to non-mTLS when any error
+        repeat
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:180]: Could we reduce the indent like this:
```
repeat
  if not ssl or 
     not ssl_client_cert or 
     not ssl_client_priv_key
  then
    break
  end
  -- fallback to non-mTLS when any error
  ...
until true
```

Comment (catbro666) [reply lib/resty/http_connect.lua:180]: The indent of this library is 4 spaces, so I chose to keep consistent with it.

Comment (chronolaw) [reply lib/resty/http_connect.lua:180]: Sorry, My mean is that we can remove the big `if ssl ... then ... end` statement, only keep `repeat ... until true`.

Comment (catbro666) [reply lib/resty/http_connect.lua:180]: Uh-oh, got it.

**Review by chronolaw — APPROVED** [review]

File: lib/resty/http_connect.lua [hunk 9]
```diff
@@ -160,22 +174,113 @@ local function connect(self, options)
...
+            ngx_log(ngx_WARN, "bad ssl_client_cert: cdata expected, got ", cert_type)
+            break
+        end
+
+        if key_type ~= "cdata" then
+            ngx_log(ngx_WARN, "bad ssl_client_priv_key: cdata expected, got ", key_type)
+            break
+        end
+
+        local status, res = xpcall(require_openssl_libs, debug.traceback)
```
Comment (Tieske) [inline lib/resty/http_connect.lua:197]: can't we load the modules once at the module level, and set a flag to check for availability of them? I find this a weird construct with an unnecessary intermediate table being returned.

File: lib/resty/http_connect.lua [hunk 10]
```diff
@@ -160,22 +174,113 @@ local function connect(self, options)
...
+    repeat
+        if not ssl or not ssl_client_cert or not ssl_client_priv_key then
+            break
+        end
+
+        local cert_type = type(ssl_client_cert)
+        local key_type = type(ssl_client_priv_key)
+
+        if cert_type ~= "cdata" then
+            ngx_log(ngx_WARN, "bad ssl_client_cert: cdata expected, got ", cert_type)
```
Comment (Tieske) [inline lib/resty/http_connect.lua:188]: Why do we only warn? if the client cert is set, it should succeed or error out imho. This could be a security vulnerability, since it automatically lowers security levels. What is the use case for continuing without mtls?

**Review by Tieske — CHANGES_REQUESTED** [review]

File: lib/resty/http_connect.lua (hunk 10 above)
Comment (catbro666) [reply lib/resty/http_connect.lua:188]: This just follows the existing behavior. If `sock:setclientcert` fails, it'll also warn and continue.

```
            ok, err = sock:setclientcert(ssl_client_cert, ssl_client_priv_key)
            if not ok then
              ngx_log(ngx_WARN, "could not set client certificate: ", err)
            end
```

This won't be a security vulnerability. Setting a client cert doesn't necessarily mean the server requires mTLS. It's the server that decides whether the client needs to send a certificate. So if the server doesn't require mTLS then the client cert won't be used even if it's set; if the server does require mTLS but the client doesn't send a valid certificate, the authentication will fail. So I think it makes some sense to warn and continue.

File: lib/resty/http_connect.lua (hunk 9 above)
Comment (catbro666) [reply lib/resty/http_connect.lua:197]: make sense.

File: lib/resty/http_connect.lua (hunk 10 above)
Comment (Tieske) [reply lib/resty/http_connect.lua:188]: That makes sense, though I still think, that if the user sets the cert to begin with, it must be valid. If not, that's an error. So either you don't set it, or you set it to something valid.

Comment (Tieske) [reply lib/resty/http_connect.lua:188]: (it is easier to relax the checks later, than to tighten them)

Comment (catbro666) [reply lib/resty/http_connect.lua:188]: agree. I'll change it to error out directly.

**Comment by Tieske** [comment]
@chronolaw can you have another look. lgtm now.

**Review by Tieske — APPROVED** [review]

File: lib/resty/http_connect.lua [hunk 11]
```diff
@@ -1,8 +1,26 @@
...
+
+local lib_chain, lib_x509, lib_pkey
+local openssl_available, res = xpcall(function()
+    lib_chain = require("resty.openssl.x509.chain")
+    lib_x509 = require("resty.openssl.x509")
+    lib_pkey = require("resty.openssl.pkey")
+end, debug.traceback)
+
+if not openssl_available then
+  ngx_log(ngx_WARN, "failed to load module `resty.openssl.*`, mTLS isn't supported without lua-resty-openssl:\n", res)
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:22]: The error message string is a little long ,could we break it into two lines?

File: lib/resty/http_connect.lua [hunk 12]
```diff
@@ -160,22 +178,80 @@ local function connect(self, options)
...
+        if not cert then
+            return nil, string_format("failed to dup the x509: %s", err)
+        end
+
+        -- convert from `void*` to `EVP_PKEY*`
+        local key, err = lib_pkey.new(ffi_cast("EVP_PKEY*", ssl_client_priv_key))
+        if not key then
+            return nil, string_format("failed to new the pkey: %s", err)
+        end
+        -- should not free the cdata passed in
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:218]: Add a blank line before it may be better.

File: lib/resty/http_connect.lua [hunk 13]
```diff
@@ -160,22 +178,80 @@ local function connect(self, options)
...
     if not poolname then
-        poolname = (request_scheme or "")
-                   .. ":" .. request_host
-                   .. ":" .. tostring(request_port)
-                   .. ":" .. tostring(ssl)
-                   .. ":" .. (ssl_server_name or "")
-                   .. ":" .. tostring(ssl_verify)
-                   .. ":" .. (proxy_uri or "")
-                   .. ":" .. (request_scheme == "https" and proxy_authorization or "")
+        poolname = string_format("%s:%s:%s:%s:%s:%s:%s:%s:%s",
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:237]: As talked above, could we keep the `..` concat operation here and get less code changed.

File: lib/resty/http_connect.lua (hunk 11 above)
Comment (catbro666) [reply lib/resty/http_connect.lua]: done

**Review by chronolaw — APPROVED** [review]
LGTM

**Comment by chronolaw** [comment]
I notice that there is some code (https://github.com/ledgetech/lua-resty-http/pull/307/files#diff-a717dcbee90c573feec0be98675c64ff06bf5bb3d8bb3d30b66b131952e22a3cR169), 
it return three values, but the client only uses two (ok, err), is it a bug? should we fix it?

**Comment by catbro666** [comment]
> I notice that there is some code (https://github.com/ledgetech/lua-resty-http/pull/307/files#diff-a717dcbee90c573feec0be98675c64ff06bf5bb3d8bb3d30b66b131952e22a3cR169), it return three values, but the client only uses two (ok, err), is it a bug? should we fix it?

Yeah, I think so.

**Review by Tieske — APPROVED** [review]

**Comment by Tieske** [comment]
@pintsized I think this is good to go now.

File: lib/resty/http_connect.lua [hunk 14]
```diff
@@ -1,8 +1,26 @@
...
+
+local lib_chain, lib_x509, lib_pkey
+local openssl_available, res = xpcall(function()
+    lib_chain = require("resty.openssl.x509.chain")
+    lib_x509 = require("resty.openssl.x509")
+    lib_pkey = require("resty.openssl.pkey")
+end, debug.traceback)
+
+if not openssl_available then
+  ngx_log(ngx_WARN, "failed to load module `resty.openssl.*`, \z
```
Comment (chronolaw) [inline lib/resty/http_connect.lua:21]: Sorry, I am not familiar with this `\z`, could I get a explain? thanks.

Comment (catbro666) [reply lib/resty/http_connect.lua:21]: '\z' skips the following span of white-space characters. For example:

```
❯ cat a.lua
print("aaa\z
  bbb")
❯ resty a.lua
aaabbb
```

Comment (chronolaw) [reply lib/resty/http_connect.lua:21]: learned, many thanks.

**Comment by pintsized** [comment]
Great work everyone, thank you!

**Comment by pintsized** [comment]
> @pintsized Could you bump a new version? Appreciate it.

`0.17.2` is now on `luarocks`. I'm having some issues with `opm`, but it will be there once resolved.
